DP_UPDATED = 'DataProvider is updated'

# Execution modes:
EXE_ONLINE = "ONLINE"
EXE_ONLINE_SS = "ONLINE_SOCKET_SERVER"  # It behaves similar to online but candles are sent using web socket server from another application
EXE_ONLINE_SS_Fast = "ONLINE_SOCKET_SERVER_FAST"  # Similar to EXE_ONLINE_SS but without db

EXE_OFFLINE_SS = "OFFLINE_SOCKET_SERVER"  # It behaves similar to online (send candle 1m in each minute)
EXE_OFFLINE_SS_FAST = "OFFLINE_SOCKET_SERVER_FAST"  # DB_Less; It needs waiting_queue in data provider process
EXE_OFFLINE_NSS = "OFFLINE_NO_SOCKET_SERVER"  # DB_Less; It needs waiting_queue in data provider process

# Order Request
SIDE_BUY = 'BUY'
SIDE_SELL = 'SELL'

# Binance order types
Bin_ORDER_TYPE_LIMIT = 'LIMIT'
Bin_ORDER_TYPE_MARKET = 'MARKET'
Bin_ORDER_TYPE_STOP_LOSS = 'STOP_LOSS'
Bin_ORDER_TYPE_STOP_LOSS_LIMIT = 'STOP_LOSS_LIMIT'
Bin_ORDER_TYPE_TAKE_PROFIT = 'TAKE_PROFIT'
Bin_ORDER_TYPE_TAKE_PROFIT_LIMIT = 'TAKE_PROFIT_LIMIT'
Bin_ORDER_TYPE_LIMIT_MAKER = 'LIMIT_MAKER'

Bin_FUTURE_ORDER_TYPE_LIMIT = 'LIMIT'
Bin_FUTURE_ORDER_TYPE_MARKET = 'MARKET'
Bin_FUTURE_ORDER_TYPE_STOP = 'STOP'
Bin_FUTURE_ORDER_TYPE_STOP_MARKET = 'STOP_MARKET'
Bin_FUTURE_ORDER_TYPE_TAKE_PROFIT = 'TAKE_PROFIT'
Bin_FUTURE_ORDER_TYPE_TAKE_PROFIT_MARKET = 'TAKE_PROFIT_MARKET'
Bin_FUTURE_ORDER_TYPE_LIMIT_MAKER = 'LIMIT_MAKER'

# Forex order types

Frx_ORDER_TYPE_BUY = 'MARKET_BUY'
Frx_ORDER_TYPE_SELL = 'MARKET_SELL'
Frx_ORDER_TYPE_BUY_LIMIT = 'BUY_LIMIT'
Frx_ORDER_TYPE_SELL_LIMIT = 'SELL_LIMIT'
Frx_ORDER_TYPE_BUY_STOP = 'BUY_STOP'
Frx_ORDER_TYPE_SELL_STOP = 'SELL_STOP'
Frx_ORDER_TYPE_BUY_STOP_LIMIT = 'BUY_STOP_LIMIT'
Frx_ORDER_TYPE_SELL_STOP_LIMIT = 'SELL_STOP_LIMIT'
Frx_ORDER_TYPE_CLOSE_BY = "CLOSE_POSITION"


# Set_point types
SET_POINT_BUY = 'SET_POINT_BUY'
SET_POINT_SELL = 'SET_POINT_SELL'


# # Downloader Source
#
# BINANCE = 'BINANCE'
# DF_BINANCE = 'DATA_FRAME_BINANCE'
# FOREX = 'FOREX'
# DF_FOREX = 'DATA_FRAME_FOREX'
